apiVersion: v1
kind: Namespace
metadata:
  name: client3-prep

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-client3-prep-whoami
  namespace: client3-prep
spec:
  selector:
    matchLabels:
      app: webapp-client3-prep-whoami
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp-client3-prep-whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: svc-client3-prep-whoami
  namespace: client3-prep
spec:
  selector:
    app: webapp-client3-prep-whoami
  ports:
    - port: 7070
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-client3-prep-ingress
  namespace: client3-prep
  annotations:
    kubernetes.io/ingress.class: nginx    
spec:
  rules:
  - host: client3.prep.azuredemo.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-client3-prep-whoami
            port:
              number: 7070